language: node_js
env:
  - PGPORT=5435
  - POSTGRES_PASSWORD=passwd
before_install:
  - docker-compose down
node_js:
  - '10'
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
